INSERT INTO back_system.setting (set_name,set_value,set_text) VALUES
	 ('swiper1','http://127.0.0.1:3000/upload/2.jpg',NULL),
	 ('swiper2','http://127.0.0.1:3000/upload/3.jpg',NULL),
	 ('swiper3','http://127.0.0.1:3000/upload/1.jpg',NULL),
	 ('swiper4','http://127.0.0.1:3000/upload/老胡.jpg',NULL),
	 ('swiper5','http://127.0.0.1:3000/upload/桌面壁纸.jpg',NULL),
	 ('swiper6','http://127.0.0.1:3000/upload/qi.jpg',NULL),
	 ('公司名称','合肥非度垃圾回收公司',NULL),
	 ('公司介绍','','<p><br></p><p style="text-align: start;">欢迎来到我们的公司介绍！</p><p style="text-align: start;">我们是一家专业的动漫设计公司，致力于为客户提供高质量的动漫产品设计和制作服务。我们的团队由一群富有创意和热情的美术设计师、动画师和音效师组成，我们能够灵活的应对各种动漫产品设计需求，为客户提供定制化的服务。我们成立于2024年，总部位于中国-安徽-合肥，目前拥有超过200多名员工，业务遍及全球多个国家和地区。</p><p style="text-align: start;">我们的动漫设计作品涵盖多个领域，包括动画、漫画、插画、游戏等，受到了社会和客户的广泛好评，我们秉承着“创意、专业、品质、服务”的理念，始终保持着高度的创作热情和专业精神，为客户提供最好的动漫设计作品。</p><p style="text-align: start;">如果您需要专业的动漫产品设计和制作服务，我们期待与您合作。</p>'),
	 ('公司架构',NULL,'<p style="text-align: justify;"><br></p><p style="text-align: justify;">在这场发布会中，小米一口气发布了小米 15 系列、澎湃 OS 2、小米平板 7、小米手表 S4、小米手环 9 Pro 等一系列令人瞩目的产品。每一款产品都仿佛是一颗闪耀的星星，各自散发着独特的魅力。</p><p style="text-align: justify;">然而，真正的主角非小米 SU7 Ultra 量产版莫属。它就像是这场盛宴中的皇冠明珠，吸引了无数目光的聚焦。小米SU7 Ultra可视作是小米SU7的高性能版本，<span style="color: rgb(0, 0, 0);">预售价为81.49万元，2025年3月正式发布。这个价格一经公布，立刻在设计媒体上引起轩然大波，不少人纷纷站出来进行讨论，甚至提出了质疑。</span></p><p style="text-align: justify;">面对来自外界对于价格的种种质疑，<strong>雷军回应称：“或许有人会讲，你们的车竟然卖到了 80 万，小米是不是有些飘飘然了？然而我们在做产品时，只会去思索它好不好？值不值？它有没有超出大家的预期？”之所以要打造 Ultra 这般强大的驾驶利器，缘由在于小米想要为那些心向巅峰性能之人、为那些憧憬快意人生之人、为那些渴望超越平凡生活之人，铸就终极的 Dream Car 。</strong></p><p style="text-align: justify;"><span style="color: rgb(0, 0, 0);">雷军还透露，小米汽车上市第3个月，交付就突破10000台，截至目前，10月单月交付量已完成20000台，预计11月提前完成全年10万辆交付目标。</span></p><p style="text-align: justify;">值得一提的是，尽管预售价令人咋舌，高达 80 万元以上，SU7 Ultra 却依然在初入市场时便获得了认同。</p><p style="text-align: justify;">在发布当晚的 10 时 42 分，小米汽车官方微博郑重宣布，SU7 Ultra 量产版预订开启仅 10 分钟，小订量就以惊人的速度突破了 3680 台。这一数字背后，蕴含着消费者对小米品牌的坚定信任以及对 SU7 Ultra 这款产品的高度期待。</p><p style="text-align: justify;"><img src="https://pics3.baidu.com/feed/b64543a98226cffc7e4b6bfb5da1919ef703ea42.jpeg@f_auto?token=215bb93b0371c7e4ec0561a91c9b909e" alt="" data-href="" style="width: 699.812px;"></p><p style="text-align: justify;"><br></p><p style="text-align: justify;">要知道，80 万元的预售价并非小数目，在如此高昂的价格门槛面前，多数消费者通常会持谨慎态度。然而，SU7 Ultra 却能在短时间内取得如此佳绩，足以证明其独特的魅力和强大的吸引力。</p>'),
	 ('公司战略',NULL,'<p>公司战略测试一下。。。。。</p><pre style="text-align: left; line-height: 1.5;"><code class="language-  language" style="text-align: left; line-height: 1.5;">314243让e''a''f''d''d''ga''s''g''eafddgasgv</code></pre><p><br></p>');
INSERT INTO back_system.setting (set_name,set_value,set_text) VALUES
	 ('公司高层',NULL,'<p><br></p><p style="text-align: start;">欢迎来到我们的公司介绍！</p><p style="text-align: start;">我们是一家专业的动漫设计公司，致力于为客户提供高质量的动漫产品设计和制作服务。我们的团队由一群富有创意和热情的美术设计师、动画师和音效师组成，我们能够灵活的应对各种动漫产品设计需求，为客户提供定制化的服务。我们成立于2024年，总部位于中国-安徽-合肥，目前拥有超过200多名员工，业务遍及全球多个国家和地区。</p><p style="text-align: start;">我们的动漫设计作品涵盖多个领域，包括动画、漫画、插画、游戏等，受到了社会和客户的广泛好评，我们秉承着“创意、专业、品质、服务”的理念，始终保持着高度的创作热情和专业精神，为客户提供最好的动漫设计作品。</p><p style="text-align: start;">如果您需要专业的动漫产品设计和制作服务，我们期待与您合作。</p>'),
	 ('部门设置','["总裁办","组织部","研发中心"]',NULL),
	 ('产品设置','["食品类","服装类","鞋帽类","日用品类"]',NULL);
